---
- name: Cron setup
  hosts: all

  tasks:
  - name: Add Cron job  
    cron:
      name: Run test script
      minute: 30
      hour: 18
      day: 15
      month: "*"
      weekday: "*"
      user: hakcer
      job: /tmp/scripts/test.sh
