---
- name: This playbook is made for installing nginx on the remote server
  hosts: all
  become: true

  tasks:
    - name: Enabling firewall
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled

    - name: reload the firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded


