---
# tasks file for fwd_service

- name: Enable a service in firewalld 
  firewalld:
    service: http
    state: enabled
    permanent: true
  become: true
  when: ansible_os_family == "RedHat"
  notify: Reload firewall
